#name: Cypress CI
#on: [push]
#jobs:
 # cypress-run:
  #  runs-on: ubuntu-latest
  #  defaults:
 #     run:
 #       working-directory: ./cypress
 #   steps:
 #   - name: Checkout
 #     uses: actions/checkout@v2.4.2
 #   - name: Install dependencies
 #     run: npm install
 #   - name: Cypress.io
  #    uses: cypress-io/github-action@v2.9.7
  #    with:
 #       working-directory: ./cypress

name: Cypress Tests
on:
 workflow_dispatch

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npm run build

      - name: Start app
        run: npm start &
        env:
          CI: true

      - name: Wait for app to start
        run: sleep 20

      - name: Run Cypress tests
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          start: npm start
          wait-on: 'http://localhost:3000'
